---
swagger: "2.0"
info:
  version: "2.0.0"
  title: "XKCD v2"
host: "xxxxxxxxxx.execute-api.us-west-2.amazonaws.com"
basePath: "/demo"
schemes:
- "https"
paths:
  /latest:
    get:
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/comic"
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: "200"
        uri: "https://xkcd.com/info.0.json"
        passthroughBehavior: "when_no_match"
        httpMethod: "GET"
        type: "http"
  /{comicId}:
    get:
      produces:
      - "application/json"
      parameters:
      - name: "comicId"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/comic"
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: "200"
        requestParameters:
          integration.request.path.comicId: "method.request.path.comicId"
        uri: "https://xkcd.com/{comicId}/info.0.json"
        passthroughBehavior: "when_no_match"
        httpMethod: "GET"
        type: "http"
definitions:
  comic:
    type: "object"
    properties:
      alt:
        type: "string"
      day:
        type: "string"
      img:
        type: "string"
      link:
        type: "string"
      month:
        type: "string"
      news:
        type: "string"
      num:
        type: "number"
      safe_title:
        type: "string"
      title:
        type: "string"
      transcript:
        type: "string"
      year:
        type: "string"
